"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
[](fg:#394260 bg:#212736)\
$git_branch\
$git_status\
[](fg:#212736 bg:#1d2230)\
$nodejs\
$rust\
$golang\
$php\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#769ff0 bg:#394260"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#212736)]($style)'

[git_status]
style = "bg:#212736"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol ($version) ](fg:#a0a9cb bg:#1d2230)]($style)'

[rust]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol ($version) ](fg:#a0a9cb bg:#1d2230)]($style)'

[golang]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol ($version) ](fg:#a0a9cb bg:#1d2230)]($style)'

[php]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol ($version) ](fg:#a0a9cb bg:#1d2230)]($style)'

